@startuml Book

!include ./book-id/book-id.plantuml
!include ./title/title.plantuml
!include ./price/price.plantuml

class "Book(書籍)" as Book << (R,red) RootEntity >> {
    BookId: BookId 
    Title: タイトル
    Price: 価格
}

Book *-down- BookId
Book *-down- Title
Book *-down- Price

@enduml